Prevent shell inception in cloud shell (#469)
## Summary

We want to prevent shell inception in both `devbox shell` and `devbox
cloud shell`.

Specifically, within regular shell and cloud shell we want to prevent
another
regular shell or cloud shell from starting.

- refactor into a common utility function, and parameterize by the
attempted
- change from vanilla golang error to `usererr`

## How was it tested?

tested in `devbox shell`:
```
(devbox)
❯ devbox shell

Error: You are already in an active devbox shell.
Run `exit` before calling `devbox shell` again. Shell inception is not supported.

(devbox)
❯ devbox cloud shell

Error: You are already in an active devbox shell.
Run `exit` before calling `devbox cloud shell` again. Shell inception is not supported.
```

I didn't test within a `devbox cloud shell`, but conceptually it should
work the
same because in the VM the user will be within a `devbox shell` again.