Removing pip plugin since it was not used.
```
% devbox add pip

Error: Package pip not found
```

we also moved `venvShellHook.sh` to a python directory.